import { ThemeProvider } from '@/components/theme-provider';
import { BaseStyles } from '@primer/react';
import { StyledComponentsRegistry } from './registry';
import './styles/app.css';
import { Toaster } from 'sonner';

export const metadata = {
  title: 'Smoasters',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Note: the focus-visible polyfill adds additional attributes to `html`
    // that cause hydration mismatch errors
    <html
      lang='en'
      suppressHydrationWarning
      data-light-theme='light'
      data-dark-theme='dark'
    >
      <body className='tw:font-default'>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <Toaster richColors />
            <BaseStyles>{children}</BaseStyles>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
